"""Campaign Constants"""

# 체험단 상태
STATUS_RECRUITING = "RECRUITING"  # 모집중
STATUS_CLOSED = "CLOSED"  # 모집종료
STATUS_SELECTED = "SELECTED"  # 선정완료

VALID_CAMPAIGN_STATUSES = [STATUS_RECRUITING, STATUS_CLOSED, STATUS_SELECTED]

# 지원 상태
APPLICATION_STATUS_APPLIED = "APPLIED"  # 지원완료
APPLICATION_STATUS_SELECTED = "SELECTED"  # 선정됨
APPLICATION_STATUS_REJECTED = "REJECTED"  # 탈락

VALID_APPLICATION_STATUSES = [
    APPLICATION_STATUS_APPLIED,
    APPLICATION_STATUS_SELECTED,
    APPLICATION_STATUS_REJECTED,
]
